In [3]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 2.9 MB/s eta 0:00:06
   -- ------------------------------------- 1.3/17.7 MB 3.3 MB/s eta 0:00:05
   ---- ----------------------------------- 2.1/17.7 MB 3.3 MB/s eta 0:00:05
   ------ --------------------------------- 2.9/17.7 MB 3.4 MB/s eta 0:00:05
   -------- ------------------------------- 3.7/17.7 MB 3.5 MB/s eta 0:00:05
   ---------- ----------------------------- 4.5/17.7 MB 3.5 MB/s eta 0:00:04
   ----------- ---------------------------- 5.2/17.7 MB 3.6 MB/s eta 0:00:04
   -------------- ------------------------- 6.3/17.7 MB 3.7 MB/s eta 0:00:04
   ---------------- ----------------------- 7.1/17.7 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 7.9/17.7 MB 3.8 MB/s eta 0:00:03
   -------------------- ------------------- 8.9/17.7 MB 3.8 MB/s eta 0:00:03
   ---------------------- ----------------- 10.0/17.7 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 11.8/17.7 MB 4.1 MB/s eta 0:00:02
   ----------------------------- ---------- 12.8/17.7 MB 4.1 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 15.5/17.7 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 16.5/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 4.1 MB/s  0:00:04
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import mysql.connector
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ganesh@3132"
)

mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")

for db in mycursor:
    print(db)

('bingeplay_dataset',)
('bookmart',)
('flipcart',)
('information_schema',)
('mysql',)
('performance_schema',)
('redflag',)
('sakila',)
('shopkart',)
('techmantra',)
('world',)

In [9]:

mycursor.execute("USE bingeplay_dataset")

sql_filename = r"C:\Users\Ganeshnayak\Downloads\12923129-Advanced_SQL_Data_set_for_MP_4 (1)\Advanced SQL Data set for MP 4.sql"

with open(sql_filename, 'r', encoding='utf-8') as f:
    sql_script = f.read()
for statement in sql_script.split(';'):
    if statement.strip():
        try:
            mycursor.execute(statement)
            if mycursor.with_rows:
                mycursor.fetchall()
        except mysql.connector.Error as err:
            print(f"Error: {err}")

mydb.commit()
mycursor.execute("SHOW TABLES")
print("Imported tables:", mycursor.fetchall())

Imported tables: [('ratings',), ('shows',), ('subscriptions',), ('users',), ('watch_sessions',)]

In [10]:
import pandas as pd
df_users = pd.read_sql("SELECT * FROM users", con=mydb)
df_shows = pd.read_sql("SELECT * FROM shows", con=mydb)
df_ratings = pd.read_sql("SELECT * FROM ratings", con=mydb)
df_subscriptions = pd.read_sql("SELECT * FROM subscriptions", con=mydb)
df_watch_sessions = pd.read_sql("SELECT * FROM watch_sessions", con=mydb)
df_users.head()

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\856973585.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_users = pd.read_sql("SELECT * FROM users", con=mydb)
C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\856973585.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_shows = pd.read_sql("SELECT * FROM shows", con=mydb)
C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\856973585.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ratings = pd.read_sql("SELECT * FROM ratings", con=mydb)
C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\856973585.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_subscriptions = pd.read_sql("SELECT * FROM subscriptions", con=mydb)
C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\856973585.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_watch_sessions = pd.read_sql("SELECT * FROM watch_sessions", con=mydb)

  user_id           name signup_date       city age_group referral_source
0  U00001      Neha Bhat  2024-06-28  Bengaluru     18-24          friend
1  U00002    Kritika Roy  2024-03-31    Chennai     25-34    social_media
2  U00003  Ishita Shenoy  2024-06-08    Chennai     18-24    social_media
3  U00004  Kritika Menon  2024-01-04       Pune     25-34    social_media
4  U00005   Kiara Bansal  2024-02-12  Ahmedabad     35-44         organic

In [11]:
df_shows.info()
df_ratings.info()
df_watch_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       100 non-null    object
 1   title         100 non-null    object
 2   category      100 non-null    object
 3   language      100 non-null    object
 4   release_year  100 non-null    int64
 5   imdb_rating   100 non-null    float64
 6   is_original   100 non-null    int64
 7   min_plan      100 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rating_id   5000 non-null   int64
 1   user_id     5000 non-null   object
 2   show_id     5000 non-null   object
 3   stars       5000 non-null   int64
 4   rated_date  5000 non-null   object
dtypes: int64(2), object(3)
memory usage: 195.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100351 entries, 0 to 100350
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   session_id     100351 non-null  int64
 1   user_id        100349 non-null  object
 2   show_id        100351 non-null  object
 3   session_date   100351 non-null  object
 4   watch_minutes  100351 non-null  int64
 5   device_type    100351 non-null  object
 6   completed      100351 non-null  int64
dtypes: int64(3), object(4)
memory usage: 5.4+ MB

In [11]:
#  TIER -1 
#  Q1 Active revenue 
#ANS 2340

In [ ]:
Q1="""SELECT count(*) as active_subsriptions, sum(monthly_price_inr) as total_monthly_revenue
from subscriptions where status='active' and (end_date is null or end_date>'2024-06-30');"""
pd.read_sql(Q1, con=mydb)

In [15]:
# Q2-signup momentum
#ans 6 rows , signup count from  350-600 from 2024-01 to 2024-06(y-m)

In [14]:
q2="""SELECT date_format(signup_date,'%Y-%m') as signup_month, count(user_id) as signup_count
from users
where signup_date between '2024-01-01' and '2024-06-30'
group by signup_month
order by signup_month;
"""
pd.read_sql(q2,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\1645429823.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(q2,con=mydb)

  signup_month  signup_count
0      2024-01           350
1      2024-02           400
2      2024-03           500
3      2024-04           550
4      2024-05           600
5      2024-06           600

In [ ]:
"""# Q3 - Device analytics 
# ans"""

In [16]:
q3="""select device_type,count(*) as total_sessions,sum(watch_minutes) as total_watch_minutes,
round(avg(watch_minutes),2) as avg_watch_minutes,round(100.0*sum(case when completed=1 then 1 else 0 end)/count(*),2)as completion_rate
from watch_sessions where user_id is not null
group by device_type
order by total_sessions desc;
"""
pd.read_sql(q3,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\2580848315.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(q3,con=mydb)

,device_type,total_sessions,total_watch_minutes,avg_watch_minutes,completion_rate
0,Mobile,50172,1504355.0,29.98,60.24
1,TV,27981,840595.0,30.04,59.98
2,Laptop,15105,453434.0,30.02,60.51
3,Tablet,7091,210733.0,29.72,59.79

In [ ]:
# Q4 - Rating distribution

In [17]:
q4="""with total as (
select count(*) as total_rating from ratings)
select stars, count(*) as rating_count,round(100.0*count(*)/(select total_rating from total),2) as percentage
from ratings group by stars
order by stars;"""
pd.read_sql(q4,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\2711955004.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(q4,con=mydb)

   stars  rating_count  percentage
0      1           234        4.68
1      2           352        7.04
2      3           847       16.94
3      4          1781       35.62
4      5          1786       35.72

In [ ]:
#Q5 - Originals vs acquired 
#ans acqired-70 shows, original-30shows

In [18]:
q5="""select
case when is_original=1 then 'Originals' else 'Acquired' end as show_type,count(*) as nums_shows,
round(avg(imdb_rating),2 )as avg_rating,
round(avg(release_year)) as avg_release_year
from shows
group by is_original;
"""
pd.read_sql(q5,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\2575090960.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(q5,con=mydb)

   show_type  nums_shows  avg_rating  avg_release_year
0   Acquired          70        6.63            2021.0
1  Originals          30        7.92            2020.0

In [21]:
##TIER-2 - Joins & Subqueries
#Q2  Binge day detection

In [19]:
Q6="""select USER_ID,SHOW_ID, DATE(SESSION_DATE)AS BINGE_DATE,
COUNT(*) AS EPISODE_COUNT
FROM watch_sessions
WHERE USER_ID IS NOT NULL
GROUP BY USER_ID,SHOW_ID,DATE(SESSION_DATE)
HAVING COUNT(*)>= 3
ORDER BY EPISODE_COUNT DESC;"""
pd.read_sql(Q6,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\2898454602.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q6,con=mydb)

    USER_ID SHOW_ID  BINGE_DATE  EPISODE_COUNT
0    U02292    S080  2024-06-30             15
1    U02048    S097  2024-05-29              8
2    U02052    S002  2024-05-15              8
3    U01694    S073  2024-04-04              8
4    U02864    S096  2024-05-05              8
..      ...     ...         ...            ...
511  U02122    S044  2024-06-28              3
512  U00218    S026  2024-06-29              3
513  U02334    S094  2024-06-29              3
514  U02514    S094  2024-06-29              3
515  U02334    S013  2024-06-29              3

[516 rows x 4 columns]

In [ ]:
##Q7 - Q1 signups who never watched (THE NULL TRAP)
##ANS 570 USERS

In [22]:
Q7="""SELECT COUNT(*)AS NEVER_WATCHED_USER
FROM USERS u 
LEFT JOIN WATCH_SESSIONS W ON U.USER_ID=W.USER_ID
WHERE U.SIGNUP_DATE BETWEEN '2024-01-01' AND '2024-06-30'
AND W.USER_ID IS NULL;
"""
pd.read_sql(Q7,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_12808\944336694.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q7,con=mydb)

   NEVER_WATCHED_USER
0                 540

In [23]:
#Q8 - The over-paying Premium/Family users
#ANS 366 USER WHOSE ENTIRE WATCH HISTORY IS BASIC-TIER ONLY

In [12]:
Q8="""SELECT S.USER_ID FROM SUBSCRIPTIONS S 
JOIN WATCH_SESSIONS W ON S.USER_ID=W.USER_ID
JOIN SHOWS SH ON W.SHOW_ID=SH.SHOW_ID
WHERE S.PLAN IN ('PREMUIM','FAMILY')
GROUP BY S.USER_ID
HAVING MIN(SH.MIN_PLAN) ='BASIC';"""
pd.read_sql(Q8,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\2191862369.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q8,con=mydb)

    USER_ID
0    U02131
1    U01963
2    U02717
3    U01646
4    U01613
..      ...
361  U01157
362  U01690
363  U00861
364  U00955
365  U02775

[366 rows x 1 columns]

In [25]:
#Q9 - Upgrade success cohort 
#ANS:13 Succesful Upgrades

In [13]:
Q9="""SELECT COUNT(DISTINCT S1.USER_ID) AS SUCCESSFUL_UPGRADES
  FROM SUBSCRIPTIONS S1
  JOIN SUBSCRIPTIONS S2
  ON S1.USER_ID=S2.USER_ID
  WHERE S1.PLAN='BASIC'
  AND S2.PLAN IN ('PREMIUM','FAMILY')
  AND DATEDIFF(S2.END_DATE,S2.START_DATE)>=60;
  """
pd.read_sql(Q9,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\570010959.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q9,con=mydb)

   SUCCESSFUL_UPGRADES
0                   13

In [ ]:
#Q10 - Cliffhanger comebacks 
#ANS:

In [15]:
Q10=""" SELECT distinct W1.USER_ID,W1.SHOW_ID
  FROM WATCH_SESSIONS W1
  WHERE W1.COMPLETED=0
  AND exists (
  SELECT 1
  FROM WATCH_SESSIONS W2
  WHERE W2.USER_ID=W1.USER_ID
  AND W2.SHOW_ID=W1.SHOW_ID
  AND W2.SESSION_DATE > W1.SESSION_DATE);"""
pd.read_sql(Q10,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\1607417335.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q10,con=mydb)

     USER_ID SHOW_ID
0     U01833    S041
1     U00411    S023
2     U02022    S097
3     U02584    S013
4     U02847    S087
...      ...     ...
9911  U02994    S054
9912  U01446    S071
9913  U01942    S030
9914  U01586    S047
9915  U02421    S088

[9916 rows x 2 columns]

In [ ]:
#Tier 3 - The Killer Questions 
#Q11-Consecutive-week engagement
#ans longest streak:26 ,users with 4+ streaks:1675

In [20]:
Q11="""WITH user_weeks AS (
    SELECT DISTINCT 
           user_id,
           YEARWEEK(session_date, 3) AS week_num
    FROM watch_sessions
    WHERE user_id IS NOT NULL
),
streaks AS (
    SELECT 
        user_id,
        week_num,
        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY week_num) AS rn
    FROM user_weeks
),
grouped AS (
    SELECT 
        user_id,
        (week_num - rn) AS grp,
        COUNT(*) AS streak_length
    FROM streaks
    GROUP BY user_id, (week_num - rn)
)
SELECT 
    COUNT(DISTINCT user_id) AS users_with_4plus_streak,
    MAX(streak_length) AS longest_streak,
    (SELECT user_id FROM grouped ORDER BY streak_length DESC LIMIT 1) AS top_user
FROM grouped
WHERE streak_length >= 4;
"""
pd.read_sql(Q11,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\1321533939.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q11,con=mydb)

   users_with_4plus_streak  longest_streak top_user
0                     1675              26   U01658

In [21]:
#Q12-Churn signal detection
#ANS:

In [24]:
Q12="""WITH user_weeks AS (
    SELECT DISTINCT 
           user_id,
           YEARWEEK(session_date, 3) AS week_num
    FROM watch_sessions
)
SELECT 
    user_id,
    MIN(week_num) AS start_week,
    MAX(week_num) AS end_week,
    COUNT(*) AS total_weeks
FROM user_weeks
GROUP BY user_id
HAVING COUNT(*) >= 4
   AND MAX(week_num) - MIN(week_num) + 1 = COUNT(*);

"""
pd.read_sql(Q12,con=mydb)

C:\Users\Ganeshnayak\AppData\Local\Temp\ipykernel_15400\2892080239.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(Q12,con=mydb)

    user_id  start_week  end_week  total_weeks
0    U01575      202418    202426            9
1    U01062      202420    202426            7
2    U00533      202414    202426           13
3    U01833      202405    202426           22
4    U02443      202415    202426           12
..      ...         ...       ...          ...
900  U02722      202422    202425            4
901  U00644      202419    202426            8
902  U01721      202422    202425            4
903  U01627      202422    202426            5
904  U00512      202421    202426            6

[905 rows x 4 columns]